apiVersion: v1
kind: Service
metadata:
  name: vasp1
  labels:
    app: trisa
    entity: vasp1
spec:
  type: NodePort
  selector:
    app: trisa
    entity: vasp1
  ports:
  - name: grpc
    port: 8091
    targetPort: grpc
    nodePort: 30091
  - name: admin
    port: 8591
    targetPort: admin
    nodePort: 30591
