apiVersion: v1
kind: Service
metadata:
  name: vasp3
  labels:
    app: trisa
    entity: vasp3
spec:
  type: NodePort
  selector:
    app: trisa
    entity: vasp3
  ports:
  - name: grpc
    port: 8093
    targetPort: grpc
    nodePort: 30093
  - name: admin
    port: 8593
    targetPort: admin
    nodePort: 30593
