apiVersion: v1
kind: Service
metadata:
  name: vasp2
  labels:
    app: trisa
    entity: vasp2
spec:
  type: NodePort
  selector:
    app: trisa
    entity: vasp2
  ports:
  - name: grpc
    port: 8092
    targetPort: grpc
    nodePort: 30092
  - name: admin
    port: 8592
    targetPort: admin
    nodePort: 30592
