kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      # VASP1
      - containerPort: 30091
        hostPort: 8091
      - containerPort: 30591
        hostPort: 8591
      # VASP2
      - containerPort: 30092
        hostPort: 8092
      - containerPort: 30592
        hostPort: 8592
      # VASP3
      - containerPort: 30093
        hostPort: 8093
      - containerPort: 30593
        hostPort: 8593