openapi: 3.0.0
info:
  version: 0.0.1
  title: TRISA Directory Service
servers:
  - url: 'https://localhost:3000'
paths:
  /vasp/{vaspId}:
    get:
      summary: 'Returns details about a particular vasp'
      operationId: getVasp
      tags:
        - vasps
      parameters:
        - name: id
          in: path
          description: ID of the VASP
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Details regarding the VASP by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vasp'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /vasps:
    get:
      summary: 'Returns a list of vasps'
      operationId: getVasp
      tags:
        - vasps
      parameters:
        - name: search
          in: query
          description: Text search for vasps
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'Details regarding the VASP by ID'
          headers:
            x-next:
              description: A JSON Array of VASP details
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vasp'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Vasp:
      type: object
      title: VASP Information
      required:
        - vaspEntity
        - vaspTrisaCertification
      properties:
        vaspEntity:
          $ref: '#/components/schemas/VaspEntity'
        vaspTrisaCertification:
          $ref: '#/components/schemas/VaspTrisaCertification'
    VaspEntity:
      type: object
      title: VASP Entity Basic Information
      description: Entity Business Information for VASPs Directory
      required:
        - vaspFullLegalName
        - vaspFullLegalAddress
        - vaspIncorporationDate
        - vaspIncorporationNumber 
      properties:
        vaspFullLegalName:
          description: The full legal name as registered business
          type: string
        vaspFullLegalAddress:
          description: The full legal address as registered business
          type: string
        vaspIncorporationDate:
          description: Date of entity incorporation
          type: string
          format: date
        vaspIncorporationNumber:
          description: Entity incorporation number
          type: string
        vaspLeiNumber:
          description: Entity LEI number (if available)
          type: string
    VaspTrisaCertification:
      type: object
      title: VASP TRISA Certification Information
      description: Relevant details of the VASP TRISA Certification
      required:
        - subjectName
        - issuerName
        - serialNumber
        - version
        - signatureAlgorithm
        - notValidBefore
        - notValidAfter
        - publicKeyInfo
      properties:
        subjectName:
          $ref: '#/components/schemas/Name'
        issuerName:
          $ref: '#/components/schemas/Name'
        serialNumber:
          type: string
          format: binary
        version:
          type: string
        signatureAlgorithm:
          type: string
        parameters:
          type: array
          items:
            type: string
        notValidBefore:
          type: string
          format: date
        notValidAfter:
          type: string
          format: date
        publicKeyInfo:
          $ref: '#/components/schemas/PublicKeyInfo'
    Name:
      type: object
      required:
        - commonName
        - countryRegion
      properties:
        commonName:
          type: string
        countryRegion:
          type: string
        organization:
          type: string
        organizationalUnit:
          type: string
        locality:
          type: string
        stateProvince:
          type: string
        serialNumber:
          type: string
        incCountryRegion:
          description: Country or Region of Incorporation
          type: string
        incStateProvince:
          description: State or Province of Incorporation
          type: string
        businessCategory:
          type: string
    PublicKeyInfo:
      type: object
      required:
        - algorithm
        - publicKey
        - exponent
        - keySize
        - keyUsage
        - signature
      properties:
        algorithm:
          type: string
        parameters:
          type: array
          items:
            type: string
        publicKey:
          type: string
          format: binary
        exponent:
          type: integer
          format: int64
        keySize:
          type: integer
        keyUsage:
          type: array
          items:
            type: string
        signature:
          type: string
          format: binary
Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string