openapi: 3.0.0
info:
  version: 0.0.1
  title: TRISA Directory Service
servers:
  - url: 'http://localhost:3000'
paths:
  /vasp/{vaspId}:
    get:
      summary: 'Returns details about a particular vasp'
      operationId: getVasp
      tags:
        - vasps
      parameters:
        - name: id
          in: path
          description: ID of the VASP
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Details regarding the VASP by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vasp'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /vasps:
    get:
      summary: 'Returns a list of vasps'
      operationId: getVasp
      tags:
        - vasps
      parameters:
        - name: search
          in: query
          description: Text search for vasps
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'Details regarding the VASP by ID'
          headers:
            x-next:
              description: A JSON Array of VASP details
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vasp'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    VaspEntity:
      type: object
      title: VASP Entity Basic Information
      description: Entity Business Information for VASPs Directory
      required:
        - vaspFullLegalName
        - vaspFullLegalAddress
        - vaspIncorporationDate
        - vaspIncorporationNumber 
      properties:
        vaspFullLegalName:
          description: The full legal name as registered business
          type: string
        vaspFullLegalAddress:
          description: The full legal address as registered business
          type: string
        vaspIncorporationDate:
          description: Date of entity incorporation
          type: string
        vaspIncorporationNumber:
          description: Entity incorporation number
          type: string
        vaspLeiNumber:
          description: Entity LEI number (if available)
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string